// Generated by GitHub Copilot
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Prode.Api.DTOs;
using System.Text.RegularExpressions;
using System.Xml.Linq;

namespace Prode.Api.Controllers;

/// <summary>
/// Aggregates and caches RSS feeds from popular Spanish-language sports portals.
/// Public endpoint — no authentication required.
/// Results are cached for 15 minutes to avoid hammering external servers.
/// </summary>
[ApiController]
[Route("api/[controller]")]
public class NewsController : ControllerBase
{
    // ── RSS sources ───────────────────────────────────────────────────────────
    private static readonly (string Name, string FeedUrl, string SiteUrl, string Color)[] Sources =
    [
        ("Olé",          "https://www.ole.com.ar/rss/ultimas-noticias/",              "https://www.ole.com.ar",          "#E8000D"),
        ("TyC Sports",   "https://www.tycsports.com/rss/noticias.rss",               "https://www.tycsports.com",       "#0057A8"),
        ("Infobae",      "https://www.infobae.com/deportes/rss/",                    "https://www.infobae.com/deportes","#E40000"),
        ("AS",           "https://feeds.as.com/mrss-s/pages/as/site/as.com/futbol/", "https://argentina.as.com",        "#D0021B"),
        ("Marca",        "https://www.marca.com/rss/portada.xml",                    "https://www.marca.com",           "#F5A623"),
    ];

    // ── In-memory cache ───────────────────────────────────────────────────────
    private static readonly SemaphoreSlim Lock = new(1, 1);
    private static List<NewsItemDto>? _cache;
    private static DateTime _cacheExpiry = DateTime.MinValue;

    private readonly IHttpClientFactory _httpFactory;

    public NewsController(IHttpClientFactory httpFactory) => _httpFactory = httpFactory;

    // ── GET /api/news ─────────────────────────────────────────────────────────

    [HttpGet]
    [AllowAnonymous]
    public async Task<IActionResult> GetNews()
    {
        if (_cache is not null && DateTime.UtcNow < _cacheExpiry)
            return Ok(_cache);

        await Lock.WaitAsync();
        try
        {
            // Double-check after acquiring lock
            if (_cache is not null && DateTime.UtcNow < _cacheExpiry)
                return Ok(_cache);

            var tasks = Sources.Select(s => FetchFeedAsync(s.Name, s.FeedUrl, s.SiteUrl, s.Color));
            var results = await Task.WhenAll(tasks);

            _cache = results
                .SelectMany(x => x)
                .OrderByDescending(n => n.PublishedAt)
                .Take(30)
                .ToList();

            _cacheExpiry = DateTime.UtcNow.AddMinutes(15);
            return Ok(_cache);
        }
        finally
        {
            Lock.Release();
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private async Task<IEnumerable<NewsItemDto>> FetchFeedAsync(
        string name, string feedUrl, string siteUrl, string color)
    {
        try
        {
            var client = _httpFactory.CreateClient();
            client.Timeout = TimeSpan.FromSeconds(8);
            client.DefaultRequestHeaders.UserAgent.ParseAdd(
                "Mozilla/5.0 (compatible; ProdeMundial2026/1.0)");

            var xml = await client.GetStringAsync(feedUrl);
            return ParseRss(xml, name, siteUrl, color);
        }
        catch
        {
            return [];
        }
    }

    private static IEnumerable<NewsItemDto> ParseRss(
        string xml, string sourceName, string sourceUrl, string sourceColor)
    {
        try
        {
            XNamespace media = "http://search.yahoo.com/mrss/";
            var doc = XDocument.Parse(xml);

            return doc.Descendants("item")
                .Select(item =>
                {
                    var title = item.Element("title")?.Value?.Trim() ?? "";

                    // RSS 2.0 uses text content; Atom uses href attribute
                    var link = (item.Element("link")?.Value?.Trim()
                             ?? item.Elements()
                                    .FirstOrDefault(e => e.Name.LocalName == "link")
                                    ?.Attribute("href")?.Value
                             ?? "").Trim();

                    // Some feeds omit scheme
                    if (!string.IsNullOrEmpty(link) && !link.StartsWith("http"))
                        link = sourceUrl;

                    var rawDesc = item.Element("description")?.Value ?? "";
                    var desc = StripHtml(rawDesc);
                    if (desc.Length > 200) desc = desc[..200] + "…";

                    var pubDateStr = item.Element("pubDate")?.Value ?? "";
                    DateTime.TryParse(pubDateStr, out var pubDate);
                    if (pubDate == default) pubDate = DateTime.UtcNow;

                    // Try multiple image sources
                    var image = item.Element("enclosure")?.Attribute("url")?.Value
                             ?? item.Element(media + "thumbnail")?.Attribute("url")?.Value
                             ?? item.Element(media + "content")?.Attribute("url")?.Value
                             ?? item.Elements()
                                    .FirstOrDefault(e => e.Name.LocalName == "thumbnail")
                                    ?.Attribute("url")?.Value;

                    return new NewsItemDto(title, desc, link, sourceName, sourceUrl, sourceColor, pubDate, image);
                })
                .Where(n => !string.IsNullOrWhiteSpace(n.Title) && n.Link.StartsWith("http"))
                .Take(8);
        }
        catch
        {
            return [];
        }
    }

    private static readonly Regex HtmlTagRx = new("<[^>]*>", RegexOptions.Compiled);

    private static string StripHtml(string input) =>
        HtmlTagRx.Replace(System.Net.WebUtility.HtmlDecode(input), " ")
                 .Replace("  ", " ")
                 .Trim();
}
