// Generated by GitHub Copilot
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Prode.Api.Data;
using Prode.Api.DTOs;

namespace Prode.Api.Controllers;

/// <summary>
/// Returns computed group-stage standings derived from the stored match results.
/// No authentication required — standings are public information.
/// </summary>
[ApiController]
[Route("api/[controller]")]
public class StandingsController : ControllerBase
{
    private readonly AppDbContext _context;

    /// <summary>
    /// The ordered list of group names for the 2026 World Cup (12 groups).
    /// </summary>
    private static readonly string[] GroupOrder =
    [
        "Group A", "Group B", "Group C", "Group D",
        "Group E", "Group F", "Group G", "Group H",
        "Group I", "Group J", "Group K", "Group L"
    ];

    public StandingsController(AppDbContext context)
    {
        _context = context;
    }

    /// <summary>
    /// GET /api/standings
    /// Returns standings for every group, computed from finished group-stage matches.
    /// </summary>
    [HttpGet]
    public async Task<IActionResult> Get()
    {
        // Load only group-stage matches that have defined teams (not TBD placeholders)
        var groupMatches = await _context.Matches
            .AsNoTracking()
            .Include(m => m.HomeTeam)
            .Include(m => m.AwayTeam)
            .Where(m =>
                m.Stage == "First Stage" &&
                m.HomeTeamId.HasValue &&
                m.AwayTeamId.HasValue)
            .ToListAsync();

        // Build a stat accumulator keyed by (group, teamId)
        var stats = new Dictionary<(string Group, int TeamId), TeamStats>();

        foreach (var match in groupMatches)
        {
            var group = match.GroupName;
            if (string.IsNullOrWhiteSpace(group)) continue;

            var homeId = match.HomeTeamId!.Value;
            var awayId = match.AwayTeamId!.Value;

            if (!stats.ContainsKey((group, homeId)))
                stats[(group, homeId)] = new TeamStats(match.HomeTeam!);
            if (!stats.ContainsKey((group, awayId)))
                stats[(group, awayId)] = new TeamStats(match.AwayTeam!);

            var home = stats[(group, homeId)];
            var away = stats[(group, awayId)];

            if (!match.IsFinished || match.HomeScore is null || match.AwayScore is null)
                continue; // match not played yet — team is registered but no stats to add

            var hg = match.HomeScore.Value;
            var ag = match.AwayScore.Value;

            home.Played++;
            away.Played++;
            home.GoalsFor += hg;
            home.GoalsAgainst += ag;
            away.GoalsFor += ag;
            away.GoalsAgainst += hg;

            if (hg > ag) { home.Won++; away.Lost++; home.Points += 3; }
            else if (hg < ag) { away.Won++; home.Lost++; away.Points += 3; }
            else { home.Drawn++; away.Drawn++; home.Points++; away.Points++; }
        }

        // Group and sort
        var result = new List<GroupStandingDto>();

        foreach (var groupName in GroupOrder)
        {
            var entries = stats
                .Where(kv => kv.Key.Group == groupName)
                .Select((kv, _) =>
                {
                    var s = kv.Value;
                    return new StandingEntryDto
                    {
                        TeamId = kv.Key.TeamId,
                        TeamName = s.Team.Name,
                        TeamCode = s.Team.Code,
                        FlagUrl = s.Team.FlagUrl,
                        Played = s.Played,
                        Won = s.Won,
                        Drawn = s.Drawn,
                        Lost = s.Lost,
                        GoalsFor = s.GoalsFor,
                        GoalsAgainst = s.GoalsAgainst,
                        GoalDifference = s.GoalsFor - s.GoalsAgainst,
                        Points = s.Points
                    };
                })
                .OrderByDescending(e => e.Points)
                .ThenByDescending(e => e.GoalDifference)
                .ThenByDescending(e => e.GoalsFor)
                .ThenBy(e => e.TeamName)
                .ToList();

            if (entries.Count == 0) continue;

            // Assign positions after sort
            for (var i = 0; i < entries.Count; i++)
                entries[i].Position = i + 1;

            result.Add(new GroupStandingDto { GroupName = groupName, Entries = entries });
        }

        return Ok(result);
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    private sealed class TeamStats
    {
        public Entities.Team Team { get; }
        public int Played { get; set; }
        public int Won { get; set; }
        public int Drawn { get; set; }
        public int Lost { get; set; }
        public int GoalsFor { get; set; }
        public int GoalsAgainst { get; set; }
        public int Points { get; set; }

        public TeamStats(Entities.Team team) => Team = team;
    }
}
