// Generated by GitHub Copilot
import { Component, signal, inject, afterNextRender } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NewsService, NewsItem } from '../../services/news.service';

@Component({
  selector: 'app-news',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './news.component.html',
  styleUrls: ['./news.component.scss']
})
export class NewsComponent {
  private svc = inject(NewsService);

  news     = signal<NewsItem[]>([]);
  loading  = signal(true);
  error    = signal<string | null>(null);
  readonly portals = this.svc.portals;
  readonly skeletons = [1, 2, 3, 4, 5, 6];

  constructor() {
    // afterNextRender only runs in the browser — avoids SSR crash with DOMParser
    afterNextRender(() => this.load());
  }

  load(): void {
    this.loading.set(true);
    this.error.set(null);
    this.svc.getNews().subscribe({
      next: (items) => { this.news.set(items); this.loading.set(false); },
      error: () => { this.error.set('No se pudieron cargar las noticias.'); this.loading.set(false); }
    });
  }

  timeAgo(dateStr: string): string {
    const diff = (Date.now() - new Date(dateStr).getTime()) / 1000;
    if (diff < 120)    return 'hace un momento';
    if (diff < 3600)   return `hace ${Math.floor(diff / 60)} min`;
    if (diff < 86400)  return `hace ${Math.floor(diff / 3600)}h`;
    if (diff < 172800) return 'ayer';
    return `hace ${Math.floor(diff / 86400)} días`;
  }

  placeholderGradient(item: NewsItem): string {
    return `linear-gradient(135deg, ${item.sourceColor}33 0%, rgba(2,8,24,0.8) 100%)`;
  }
}

