// Generated by GitHub Copilot
import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { environment } from '../../environments/environment';

@Injectable({
  providedIn: 'root'
})
export class ApiService {

  private http = inject(HttpClient);

  private apiUrl = environment.apiUrl;

  getTest() {
    return this.http.get(`${this.apiUrl}/test`);
  }
}
