// Generated by GitHub Copilot
import { Injectable } from '@angular/core';
import { from, forkJoin, Observable, of } from 'rxjs';
import { map, catchError } from 'rxjs/operators';

export interface NewsItem {
  title: string;
  description: string;
  link: string;
  source: string;
  sourceUrl: string;
  sourceColor: string;
  publishedAt: string;
  imageUrl: string | null;
}

// allorigins.win: /get returns JSON wrapper {contents}, /raw returns the XML directly
const ALLORIGINS_JSON = 'https://api.allorigins.win/get?url=';
const ALLORIGINS_RAW  = 'https://api.allorigins.win/raw?url=';

// Use general sports feeds and rely on keyword filtering for Mundial content
const FEEDS: { name: string; url: string; siteUrl: string; color: string }[] = [
  { name: 'Olé',        url: 'https://www.ole.com.ar/rss/ultimas-noticias/',              siteUrl: 'https://www.ole.com.ar',          color: '#E8000D' },
  { name: 'TyC Sports', url: 'https://www.tycsports.com/rss/noticias.rss',               siteUrl: 'https://www.tycsports.com',        color: '#0057A8' },
  { name: 'Infobae',    url: 'https://www.infobae.com/deportes/rss/',                    siteUrl: 'https://www.infobae.com/deportes', color: '#E40000' },
  { name: 'AS',         url: 'https://feeds.as.com/mrss-s/pages/as/site/as.com/futbol/', siteUrl: 'https://argentina.as.com',         color: '#D0021B' },
  { name: 'Marca',      url: 'https://www.marca.com/rss/portada.xml',                    siteUrl: 'https://www.marca.com',            color: '#F5A623' },
];

// Strict Mundial keywords — avoid standalone words that match club football
const MUNDIAL_KEYWORDS = [
  'mundial', 'world cup', 'copa del mundo', 'worldcup',
  'selección argentina', 'seleccion argentina', 'albiceleste',
  'messi', 'scaloni', 'di maría', 'di maria', 'lautaro', 'enzo fernández',
  'eliminatorias conmebol', 'eliminatoria sudamericana',
  'fase de grupos', 'octavos de final', 'cuartos de final', 'semifinal',
  'usa 2026', 'estados unidos 2026', 'canada 2026', 'méxico 2026',
  'fifa world', 'sede del mundial', 'estadio del mundial',
  'seleccion brasileira', 'selección brasileira',
  'seleccion española', 'selección española',
  'seleccion francesa', 'selección francesa',
  'seleccion alemana', 'selección alemana',
  'seleccion inglesa', 'selección inglesa',
  'selección', // broad but catches most national team news
];

// Club keywords to explicitly exclude (Argentina local league)
const CLUB_EXCLUSIONS = [
  'river plate', 'boca juniors', 'racing club', 'independiente',
  'san lorenzo', 'huracan', 'huracán', 'vélez', 'velez',
  'estudiantes', 'gimnasia', 'newells', 'rosario central',
  'talleres', 'belgrano', 'tigre', 'platense',
  'liga profesional', 'copa de la liga', 'superliga',
];

function isMundialRelated(title: string, desc: string): boolean {
  const text = (title + ' ' + desc).toLowerCase();
  const hasClub = CLUB_EXCLUSIONS.some(k => text.includes(k));
  if (hasClub) return false;
  return MUNDIAL_KEYWORDS.some(k => text.includes(k));
}

@Injectable({ providedIn: 'root' })
export class NewsService {

  readonly portals = FEEDS.map(f => ({ name: f.name, url: f.siteUrl, color: f.color }));

  getNews(): Observable<NewsItem[]> {
    const requests = FEEDS.map(feed =>
      from(this.fetchFeed(feed)).pipe(catchError(() => of([] as NewsItem[])))
    );

    return forkJoin(requests).pipe(
      map(results =>
        // Each feed already returns max 2 Mundial items; merge and sort by date
        results
          .flat()
          .sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime())
      )
    );
  }

  private async fetchFeed(feed: typeof FEEDS[number]): Promise<NewsItem[]> {
    const encoded = encodeURIComponent(feed.url);

    // Attempt 1: allorigins /get — returns { contents: '<xml>' }
    try {
      const res = await fetch(`${ALLORIGINS_JSON}${encoded}`, { signal: AbortSignal.timeout(8000) });
      if (res.ok) {
        const data: { contents: string } = await res.json();
        if (data?.contents) {
          const items = this.parseRss(data.contents, feed);
          if (items.length > 0) return items;
        }
      }
    } catch { /* fall through */ }

    // Attempt 2: allorigins /raw — returns the XML directly as text
    try {
      const res = await fetch(`${ALLORIGINS_RAW}${encoded}`, { signal: AbortSignal.timeout(8000) });
      if (res.ok) {
        const xml = await res.text();
        if (xml) {
          const items = this.parseRss(xml, feed);
          if (items.length > 0) return items;
        }
      }
    } catch { /* give up */ }

    return [];
  }

  private parseRss(xml: string, feed: typeof FEEDS[number]): NewsItem[] {
    try {
      const doc = new DOMParser().parseFromString(xml, 'text/xml');
      const items = Array.from(doc.querySelectorAll('item'));
      const mapped = items.map(item => {
        const title    = item.querySelector('title')?.textContent?.trim() ?? '';
        const link     = item.querySelector('link')?.textContent?.trim()
                      || item.querySelector('guid')?.textContent?.trim()
                      || feed.siteUrl;
        const pubDate  = item.querySelector('pubDate')?.textContent?.trim() ?? '';
        const rawDesc  = item.querySelector('description')?.textContent ?? '';
        const desc     = this.stripHtml(rawDesc);
        const shortDesc = desc.length > 200 ? desc.slice(0, 200) + '…' : desc;

        const mediaThumb   = item.getElementsByTagNameNS('http://search.yahoo.com/mrss/', 'thumbnail')[0];
        const mediaContent = item.getElementsByTagNameNS('http://search.yahoo.com/mrss/', 'content')[0];
        const enclosure    = item.querySelector('enclosure');
        const imageUrl     = mediaThumb?.getAttribute('url')
                          ?? mediaContent?.getAttribute('url')
                          ?? (enclosure?.getAttribute('type')?.startsWith('image') ? enclosure.getAttribute('url') : null)
                          ?? this.extractImgFromHtml(rawDesc);

        return {
          title,
          description: shortDesc,
          link: link.startsWith('http') ? link : feed.siteUrl,
          source: feed.name,
          sourceUrl: feed.siteUrl,
          sourceColor: feed.color,
          publishedAt: pubDate ? new Date(pubDate).toISOString() : new Date().toISOString(),
          imageUrl,
        } satisfies NewsItem;
      }).filter(n => !!n.title && !!n.link);

      // Only return Mundial-related items — no fallback to local football
      return mapped.filter(n => isMundialRelated(n.title, n.description)).slice(0, 2);
    } catch {
      return [];
    }
  }

  private extractImgFromHtml(html: string): string | null {
    const match = html.match(/<img[^>]+src=["']([^"']+)["']/i);
    return match?.[1] ?? null;
  }

  private stripHtml(html: string): string {
    return html.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
  }
}
