// Generated by GitHub Copilot
using Prode.Api.Services;

namespace Prode.Api.BackgroundServices;

/// <summary>
/// Periodically polls the FIFA API to sync match scores so that
/// group standings stay up-to-date as the tournament progresses.
/// The interval is configurable via <c>FixtureSync:ScoreSyncIntervalMinutes</c>
/// (default: 5 minutes).
/// </summary>
public class FifaScoreSyncBackgroundService : BackgroundService
{
    private readonly IServiceProvider _services;
    private readonly ILogger<FifaScoreSyncBackgroundService> _logger;
    private readonly TimeSpan _interval;

    public FifaScoreSyncBackgroundService(
        IServiceProvider services,
        ILogger<FifaScoreSyncBackgroundService> logger,
        IConfiguration configuration)
    {
        _services = services;
        _logger = logger;

        var minutes = configuration.GetValue<int>(
            "FixtureSync:ScoreSyncIntervalMinutes", 5);

        _interval = TimeSpan.FromMinutes(Math.Max(1, minutes));
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        // Let the startup sync finish first, then start the periodic loop.
        await Task.Delay(TimeSpan.FromSeconds(30), stoppingToken);

        _logger.LogInformation(
            "FIFA score sync background service started — interval: {Interval}",
            _interval);

        while (!stoppingToken.IsCancellationRequested)
        {
            await SyncScoresAsync(stoppingToken);
            await Task.Delay(_interval, stoppingToken);
        }
    }

    private async Task SyncScoresAsync(CancellationToken stoppingToken)
    {
        try
        {
            using var scope = _services.CreateScope();
            var syncService =
                scope.ServiceProvider.GetRequiredService<FifaFixtureSyncService>();

            var result = await syncService.SyncWorldCup2026Async(stoppingToken);

            _logger.LogInformation(
                "FIFA score sync completed — {Matches} matches, {Teams} teams",
                result.Matches,
                result.Teams);
        }
        catch (OperationCanceledException)
        {
            // Normal shutdown.
        }
        catch (Exception ex)
        {
            // Log but do not crash; will retry on next interval.
            _logger.LogWarning(ex, "FIFA score sync failed, will retry in {Interval}", _interval);
        }
    }
}
