services:
  - type: web
    name: prode-api
    env: docker
    rootDir: Prode.Api
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Database__AutoMigrate
        value: true
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__Key
        generateValue: true
      - key: Cors__AllowedOrigins__0
        value: https://prode-mundial-2026-ecru.vercel.app
