// Generated by GitHub Copilot
namespace Prode.Api.DTOs;

/// <summary>Represents a group with its standings table.</summary>
public class GroupStandingDto
{
    public string GroupName { get; set; } = string.Empty;
    public List<StandingEntryDto> Entries { get; set; } = [];
}
