// Generated by GitHub Copilot
namespace Prode.Api.Entities;

public enum MembershipStatus { Pending, Approved, Rejected }

/// <summary>Many-to-many link between a User and a PrivateGroup, with approval flow.</summary>
public class GroupMembership
{
    public int Id { get; set; }

    public int GroupId { get; set; }

    public PrivateGroup Group { get; set; } = null!;

    public Guid UserId { get; set; }

    public User User { get; set; } = null!;

    public MembershipStatus Status { get; set; } = MembershipStatus.Pending;

    public DateTime RequestedAt { get; set; } = DateTime.UtcNow;

    public DateTime? ReviewedAt { get; set; }
}
